# Generated by Django 5.2.8 on 2025-11-30 20:39

import django.db.models.deletion
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Клас')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('file', models.FileField(blank=True, null=True, upload_to=submissions.models.submission_upload_path, verbose_name='Файл')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата здачі')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Оцінка')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.classgroup', verbose_name='Клас')),
            ],
            options={
                'verbose_name': 'Робота',
                'verbose_name_plural': 'Роботи',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
