# Generated by Django 5.2.8 on 2025-12-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_options_submission_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submission', 'Здача роботи'), ('grading', 'Оцінювання'), ('comment', 'Коментар'), ('login', 'Вхід в систему')], max_length=20, verbose_name='Тип дії')),
                ('description', models.TextField(verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Журнал дій',
                'verbose_name_plural': 'Журнал дій',
                'ordering': ['-timestamp'],
            },
        ),
    ]
